# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    xamarin_update_configuration(
property: 'CodesignKey',
value: 'iApple Distribution: Medicom Innovation Partner A/S (4A42X7FYTN)',
xamarin_project_file: '/Users/susingh/.jenkins/workspace/FastlaneApp18Aug/JenkinsFastLaneTestApp/JenkinsFastLaneTestApp.iOS/JenkinsFastLaneTestApp.iOS.csproj',
build_type: ‘Release’,
platform: 'iPhone'
)

xamarin_update_configuration(
property: 'CodesignProvision',
value: 'IDA0093 MobileApp Provisioning Profile',
xamarin_project_file: '/Users/susingh/.jenkins/workspace/FastlaneApp18Aug/JenkinsFastLaneTestApp/JenkinsFastLaneTestApp.iOS/JenkinsFastLaneTestApp.iOS.csproj',
build_type: 'Release',
platform: 'iPhone'
)

  
# build your iOS app
 xamarin_build(
    solution: '/Users/susingh/.jenkins/workspace/FastlaneApp18Aug/JenkinsFastLaneTestApp/JenkinsFastLaneTestApp.sln',
    platform: 'iPhone',
    target: 'Build',
    project: 'JenkinsFastLaneTestApp.iOS',
    build_type: 'Release',
    print_all: true
  )

  end
end
